var Difficulty = "easy";
var EnemySpawnTimeDecrement = 1;
var EnemySpawnBias = 0.5;
var EnemyHealthMultiplier = 1;
var EnemySpeedMultiplier = 1;
var ProjectileSpeedMultiplier = 1;
var ProjectileColor = "white";
var PlayerColor = "white";
var PlayerRadius = 10;
var BackgroundColor = "0,0,0";
var ParticleFriction = 0.99;
var ParticleMultiplier = 2;
var ParticleSpeed = 5;
var ParticleFadeSpeedMultiplier = 1;
var ParticlesDamageEnemies = false;
var MaxEnemies = 10;
//# sourceMappingURL=vars.js.map